### ISSUE TITLE
Column and table names cannot be a reserved keyword

### ISSUE THREAD

**Issue by berkerpeksag** [ahmetb/orman#21]

**Comment by ahmetb** [comment]
Issues to consider:
- A list of reserved keywords from SQLite and MySQL. 
- Case-sensitivity: insentivity is better in this case.
- Where to store: Can be statically hard-coded in a java file or a `.properties` file with one word per line is better, can be read once and cached for future requests, also can be embeddable in `JAR`.
- When to check: Just after when MappingSession calls `scheme.checkConflictingFields(e)`. then we'll call the following: 
- Where to implement: in `org.orman.mapper` with a static method. also an exception should be created under `org.orman.mapper.exception`.

Someone needed to implement this.

**Comment by ahmetb** [comment]
Issue solved.
