### ISSUE TITLE
Loop problem with Object.object

### ISSUE THREAD

**Issue by almozavr** [ahmetb/orman#30]
If an entity e.g. Message contains ref. entity Message as a field there is a loop exception.

``` java

@entity
public class Message extends Model{

    @PrimaryKey(autoIncrement = true)
    public int rowId;
    public int title;
    public int text;
    public Message parentMessage;

    public Message{
    }
}
```

I tried to set `@OneToOne(load = LoadingPolicy.LAZY)` for `parentMessage` but it doesn't help at all.

**Comment by ahmetb** [comment]
Sorry I didn't see you created a separate issue. Already explained it in issue #31. You can follow it from there.

**Comment by almozavr** [comment]
No problem, thanks! Hope it would be fixed — this is the last thing that prevents me from using ORMan in production development...
