### ISSUE TITLE
Delay database connections in DBMS adapters

### ISSUE THREAD

**Issue by ahmetb** [ahmetb/orman#8]
We should delay establishing connections to DBMSes (if necessary) until `MappingSession.start()` since it is a blocking task and should not run upon initialization of  adapter (which is an `org.orman.datasource.Database` implementation).

**Comment by ahmetb** [comment]
DBMS `QueryExecutionContainerImpl`s using `OnDemandConnection` class are subject to throw unhandled `NullPointerException` when their `close()` method is called without any database operation that requires database to be initialized lazily.

Saw this in my dream this morning, not tested but it seems so. Can you fix this? Thanks.

**Comment by 0ffffffffh** [comment]
ok. i will take care of it soon. thanks for feedback.

**Comment by 0ffffffffh** [comment]
berker, thanks for that bug fix.
