### ISSUE TITLE
Automatic @Entity scan in enclosing project without package name

### ISSUE THREAD

**Issue by ahmetb** [ahmetb/orman#9]
An idea to implement in the future,

The framework may scan the current project for `@Entity`-annotated classes without registering an explicit package name.  Issues to consider:
- How can we implement such a thing. 
- How framework users can disable that? (maybe if an entity is manually registered, we don't scan.)
- If we implement when should this be done in during mapping session? (maybe if no entities manually registered, just before `.start()`.)

**Comment by ahmetb** [comment]
Awesome contribution. World is a better place thanks to you. (:

Thanks for all Oguz.

**Comment by 0ffffffffh** [comment]
i'm glad to be useful. :)
